version: 0.1
component: build
timeoutInSeconds: 600
runAs: root
shell: bash
env:
  variables:
    key: "value"
  exportedVariables:
    - BUILDRUN_HASH

steps:
  - type: Command
    name: "Export variables step"
    timeoutInSeconds: 40
    command: |
      export BUILDRUN_HASH=`echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7`
      echo "BUILDRUN_HASH: " $BUILDRUN_HASH
    onFailure:
      - type: Command
        command: echo "build failed"
        timeoutInSeconds: 40
        runAs: root
  - type: Command
    name: "gradlew build step"
    timeoutInSeconds: 600
    command: |
      cd ${OCI_WORKSPACE_DIR}/micronaut-java-build/hello-world-java
      chmod 777 ./gradlew
      ./gradlew clean build
      echo "Wo hoo build got successfully completed"
    onFailure:
      - type: Command
        command: echo "build failed"
        timeoutInSeconds: 40
        runAs: root
  - type: Command
    timeoutInSeconds: 1200
    name: "Build Container Image"
    command: |
      cd ${OCI_WORKSPACE_DIR}/micronaut-java-build/hello-world-java
      docker build --pull --rm -t micronaut-java -f Dockerfile .
    onFailure:
      - type: Command
        command: |
          echo "Handling Failure"
          echo "Failure successfully handled"
        timeoutInSeconds: 40
        runAs: root

outputArtifacts:
  - name: output
    type: DOCKER_IMAGE
    # this location tag doesn't effect the tag used to deliver the container image
    # to the Container Registry
    location: micronaut-java:latest

